apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/
- ingress-route.yaml
- certificate.yaml

patches:
- path: config-map.yaml
- path: deployment.yaml
images:
- digest: sha256:ac09f537ab7f0968e278e02c28eac59e09d9bb3f6e72d5c765bf3d6d746580db
  name: ghcr.io/pablitxn/browser-gpt:dev
  newName: ghcr.io/pablitxn/browser-gpt
