apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/
- ingress-route.yaml

patches:
- path: config-map.yaml
- path: deployment.yaml
images:
- name: ghcr.io/pablitxn/browser-gpt:prod
  newName: ghcr.io/pablitxn/browser-gpt
